<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Midtrans-Sofie" time="10.946" tests="2" failures="0" errors="1">
   <testsuite name="Midtrans-Sofie" tests="2" failures="0" errors="1" time="10.946" skipped="0" timestamp="2021-07-26 20:43:23" hostname="arisahazriaty - 192.168.1.2" id="Test Suites/Midtrans-Sofie">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="/Users/arisahazriaty/Katalon Studio/ProjectMidtrans/Reports/20210726_204306/Midtrans-Sofie/20210726_204306"/>
         <property name="logFiles" value="/Users/arisahazriaty/Katalon Studio/ProjectMidtrans/Reports/20210726_204306/Midtrans-Sofie/20210726_204306/execution0.log"/>
         <property name="attachments" value=""/>
         <property name="hostName" value="arisahazriaty - 192.168.1.2"/>
         <property name="os" value="Mac OS X 64bit"/>
         <property name="katalonVersion" value="8.0.5.208"/>
         <property name="browser" value="Chrome 91.0.4472.164"/>
         <property name="hostAddress" value="192.168.1.2"/>
         <property name="sessionId" value="0280038c388f6ac7cd55127a2bb5d200"/>
         <property name="seleniumVersion" value="3.141.59"/>
         <property name="proxyInformation" value="ProxyInformation { proxyOption=NO_PROXY, proxyServerType=HTTP, username=, password=********, proxyServerAddress=, proxyServerPort=0, executionList=&quot;&quot;, isApplyToDesiredCapabilities=true }"/>
         <property name="platform" value="Mac OS X"/>
      </properties>
      <testcase name="Test Cases/Midtrans001-Positive" time="8.618" classname="Test Cases/Midtrans001-Positive" status="PASSED">
         <system-out><![CDATA[2021-07-26 20:43:24 - [TEST_CASE][PASSED] - Test Cases/Midtrans001-Positive: Test Cases/Midtrans001-Positive

2021-07-26 20:43:24 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

2021-07-26 20:43:25 - [MESSAGE][INFO] - Starting 'Chrome' driver

2021-07-26 20:43:25 - [MESSAGE][INFO] - Action delay is set to 0 milliseconds

2021-07-26 20:43:30 - [MESSAGE][PASSED] - Browser is opened with url: ''

2021-07-26 20:43:30 - [TEST_STEP][PASSED] - maximizeWindow(): Current window maximized

2021-07-26 20:43:30 - [MESSAGE][PASSED] - Current window maximized

2021-07-26 20:43:30 - [TEST_STEP][PASSED] - navigateToUrl(baseURL): Navigate to 'https://demo.midtrans.com/' successfully

2021-07-26 20:43:32 - [MESSAGE][PASSED] - Navigate to 'https://demo.midtrans.com/' successfully]]></system-out>
         <system-err><![CDATA[]]></system-err>
      </testcase>
      <testcase name="Test Cases/Sofie-Case-Positive" time="1.396" classname="Test Cases/Sofie-Case-Positive" status="ERROR">
         <error type="ERROR" message="Test Cases/Sofie-Case-Positive FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/null' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/null' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at Sofie-Case-Positive.run(Sofie-Case-Positive:20)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:369)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:360)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:339)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:248)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:191)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:140)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:89)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:185)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1627306986542.run(TempTestSuite1627306986542.groovy:39)
"/>
         <system-out><![CDATA[2021-07-26 20:43:32 - [TEST_CASE][ERROR] - Test Cases/Sofie-Case-Positive: Test Cases/Sofie-Case-Positive FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/null' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/null' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at Sofie-Case-Positive.run(Sofie-Case-Positive:20)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:369)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:360)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:339)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:248)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:191)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:140)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:89)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:185)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1627306986542.run(TempTestSuite1627306986542.groovy:39)


2021-07-26 20:43:34 - [TEST_STEP][PASSED] - data = findTestData("null"): null]]></system-out>
         <system-err><![CDATA[2021-07-26 20:43:32 - [TEST_CASE][ERROR] - Test Cases/Sofie-Case-Positive: Test Cases/Sofie-Case-Positive FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/null' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/null' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at Sofie-Case-Positive.run(Sofie-Case-Positive:20)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:369)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:360)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:339)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:248)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:191)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:140)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:89)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:185)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1627306986542.run(TempTestSuite1627306986542.groovy:39)]]></system-err>
      </testcase>
      <system-out><![CDATA[2021-07-26 20:43:23 - [TEST_SUITE][ERROR] - Midtrans-Sofie: Test Cases/Sofie-Case-Positive FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/null' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/null' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at Sofie-Case-Positive.run(Sofie-Case-Positive:20)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:369)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:360)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:339)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:248)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:191)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:140)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:89)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:185)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1627306986542.run(TempTestSuite1627306986542.groovy:39)]]></system-out>
      <system-err><![CDATA[2021-07-26 20:43:23 - [TEST_SUITE][ERROR] - Midtrans-Sofie: Test Cases/Sofie-Case-Positive FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/null' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/null' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at Sofie-Case-Positive.run(Sofie-Case-Positive:20)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:369)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:360)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:339)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:248)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:191)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:140)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:89)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:185)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1627306986542.run(TempTestSuite1627306986542.groovy:39)]]></system-err>
   </testsuite>
</testsuites>
